export const users = [
  {
    email: "user_3@example.com",
    emailVerified: true,
    phoneNumber: "+112345679679",
    password: "secretPassword",
    displayName: "Michael Smith",
    photoURL: "http://www.example.com/12345679/photo.png",
    disabled: false,
  },
  {
    email: "user_4@example.com",
    emailVerified: false,
    phoneNumber: "+112345679680",
    password: "secretPassword",
    displayName: "Sarah Johnson",
    photoURL: "http://www.example.com/12345680/photo.png",
    disabled: false,
  },
  {
    email: "user_5@example.com",
    emailVerified: true,
    phoneNumber: "+112345679681",
    password: "secretPassword",
    displayName: "David Brown",
    photoURL: "http://www.example.com/12345681/photo.png",
    disabled: false,
  },
  {
    email: "user_6@example.com",
    emailVerified: false,
    phoneNumber: "+112345679682",
    password: "secretPassword",
    displayName: "Emily Davis",
    photoURL: "http://www.example.com/12345682/photo.png",
    disabled: false,
  },
  {
    email: "user_7@example.com",
    emailVerified: true,
    phoneNumber: "+112345679683",
    password: "secretPassword",
    displayName: "Daniel Wilson",
    photoURL: "http://www.example.com/12345683/photo.png",
    disabled: false,
  },
  {
    email: "user_8@example.com",
    emailVerified: false,
    phoneNumber: "+112345679684",
    password: "secretPassword",
    displayName: "Olivia Martinez",
    photoURL: "http://www.example.com/12345684/photo.png",
    disabled: false,
  },
  {
    email: "user_9@example.com",
    emailVerified: true,
    phoneNumber: "+112345679685",
    password: "secretPassword",
    displayName: "James Anderson",
    photoURL: "http://www.example.com/12345685/photo.png",
    disabled: false,
  },
  {
    email: "user_10@example.com",
    emailVerified: false,
    phoneNumber: "+112345679686",
    password: "secretPassword",
    displayName: "Sophia Thomas",
    photoURL: "http://www.example.com/12345686/photo.png",
    disabled: false,
  },
  {
    email: "user_11@example.com",
    emailVerified: true,
    phoneNumber: "+112345679687",
    password: "secretPassword",
    displayName: "Christopher Taylor",
    photoURL: "http://www.example.com/12345687/photo.png",
    disabled: false,
  },
  {
    email: "user_12@example.com",
    emailVerified: false,
    phoneNumber: "+112345679688",
    password: "secretPassword",
    displayName: "Ava Moore",
    photoURL: "http://www.example.com/12345688/photo.png",
    disabled: false,
  },
  {
    email: "user_13@example.com",
    emailVerified: true,
    phoneNumber: "+112345679689",
    password: "secretPassword",
    displayName: "Matthew Jackson",
    photoURL: "http://www.example.com/12345689/photo.png",
    disabled: false,
  },
  {
    email: "user_14@example.com",
    emailVerified: false,
    phoneNumber: "+112345679690",
    password: "secretPassword",
    displayName: "Isabella White",
    photoURL: "http://www.example.com/12345690/photo.png",
    disabled: false,
  },
  {
    email: "user_15@example.com",
    emailVerified: true,
    phoneNumber: "+112345679691",
    password: "secretPassword",
    displayName: "Joshua Harris",
    photoURL: "http://www.example.com/12345691/photo.png",
    disabled: false,
  },
  {
    email: "user_16@example.com",
    emailVerified: false,
    phoneNumber: "+112345679692",
    password: "secretPassword",
    displayName: "Mia Clark",
    photoURL: "http://www.example.com/12345692/photo.png",
    disabled: false,
  },
  {
    email: "user_17@example.com",
    emailVerified: true,
    phoneNumber: "+112345679693",
    password: "secretPassword",
    displayName: "Andrew Lewis",
    photoURL: "http://www.example.com/12345693/photo.png",
    disabled: false,
  },
  {
    email: "user_18@example.com",
    emailVerified: false,
    phoneNumber: "+112345679694",
    password: "secretPassword",
    displayName: "Charlotte Walker",
    photoURL: "http://www.example.com/12345694/photo.png",
    disabled: false,
  },
  {
    email: "user_19@example.com",
    emailVerified: true,
    phoneNumber: "+112345679695",
    password: "secretPassword",
    displayName: "Ryan Hall",
    photoURL: "http://www.example.com/12345695/photo.png",
    disabled: false,
  },
  {
    email: "user_20@example.com",
    emailVerified: false,
    phoneNumber: "+112345679696",
    password: "secretPassword",
    displayName: "Amelia Young",
    photoURL: "http://www.example.com/12345696/photo.png",
    disabled: false,
  },
  {
    email: "user_21@example.com",
    emailVerified: true,
    phoneNumber: "+112345679697",
    password: "secretPassword",
    displayName: "Benjamin King",
    photoURL: "http://www.example.com/12345697/photo.png",
    disabled: false,
  },
  {
    email: "user_22@example.com",
    emailVerified: false,
    phoneNumber: "+112345679698",
    password: "secretPassword",
    displayName: "Harper Wright",
    photoURL: "http://www.example.com/12345698/photo.png",
    disabled: false,
  },
];
